name: problem2
channels:
  - defaults
dependencies:
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py37_0
  - openssl=1.1.1g=he774522_0
  - pip=20.0.2=py37_3
  - python=3.7.7=h81c818b_4
  - setuptools=46.4.0=py37_0
  - sqlite=3.31.1=h2a8f88b_1
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_2
  - wheel=0.34.2=py37_0
  - wincertstore=0.2=py37_0
  - zlib=1.2.11=h62dcd97_4
  - pip:
    - pyqt5==5.14.2
    - pyqt5-sip==12.7.2
prefix: C:\Users\Alaa gamal\Anaconda3\envs\problem2

